#!/bin/bash
echo "Starting scheduler"
luigid --background --pidfile /luigi_files/pidfile --logdir /luigi_files/log_dir/ --state-path /luigi_files/statefile;
echo "Start training";
luigi --module train TrainLogRegAllWrapperTask;