#!/bin/bash
echo "Starting scheduler";
luigid --background --pidfile /home/worker/luigi_files/pidfile --logdir /home/worker/luigi_files/log_dir/ --state-path /home/worker/luigi_files/statefile &
echo "Start training";
luigi --module train TrainLogRegAllWrapperTask